Repository codestates-seb/seb39_main_012, pull requests merged in 2022-09, with the labels that each got.

#11 Feat : 회원가입 레이아웃 및 유효성 검사 로직 추가
  client/components/CheckBox/CheckBox.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Layout.tsx
  client/components/SignUp/AgreeBox.tsx
  client/components/SignUp/CheckBoxLabel.tsx
  client/components/SignUp/UserForm.tsx
  client/pages/signup/index.tsx
  client/utils/validate/index.ts
Labels: 🎁 기능추가, 🖍 레이아웃

#12 Feat : 로그인 레이아웃 및 기능 , 소셜 로그인 버튼 추가
  client/components/AuthButton/AuthButton.tsx
  client/components/Input/Input.tsx
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/SocialAuthButtons/SocialAuthButtons.tsx
  client/pages/login/index.tsx
  client/public/images/authApple.png
  client/public/images/authFacebook.png
  client/public/images/authGoogle.png
  client/public/images/authKakao.png
  client/public/images/authNaver.png
Labels: 🎁 기능추가, 🖍 레이아웃

#13 Feat : 로그인 , 회원가입 페이지 레이아웃 추가 , 유효성 검사 로직 및 공통 컴포넌트 생성
  client/components/AuthButton/AuthButton.tsx
  client/components/CheckBox/CheckBox.tsx
  client/components/Input/Input.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/SignUp/AgreeBox.tsx
  client/components/SignUp/CheckBoxLabel.tsx
  client/components/SignUp/Postcode.tsx
  client/components/SignUp/SignUpTab.tsx
  client/components/SignUp/UserForm.tsx
  client/components/SocialAuthButtons/SocialAuthButtons.tsx
  client/components/Test.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/signup/index.tsx
  client/public/images/authApple.png
  client/public/images/authFacebook.png
  client/public/images/authGoogle.png
  client/public/images/authKakao.png
  client/public/images/authNaver.png
  client/styles/GlobalStyle.ts
  client/styles/colors.ts
  client/styles/css.ts
  client/utils/validate/index.ts
Labels: 🎁 기능추가, 🖍 레이아웃

#20 Feat : 회원가입 백엔드 기능 추가 , 이메일 중복 체크 기능 추가 , 헤더 컴포넌트 생성
  client/components/AuthButton/AuthButton.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Header/Header.tsx
  client/components/Layout/Header/Search.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/LoginForm.tsx
  client/components/SignUp/AgreeBox.tsx
  client/components/SignUp/UserForm.tsx
  client/hooks/useDebounce.tsx
  client/hooks/useScreenX.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/auth/check.ts
  client/pages/api/auth/db.ts
  client/pages/api/auth/login.ts
  client/pages/api/auth/signup.ts
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/signup/index.tsx
  client/public/svg/Logoimg.png
  client/public/svg/MoblieLogo.png
Labels: 🎁 기능추가, 🖍 레이아웃, 🧲 API 연결

#21 Feat : 상세 페이지 레이아웃 및 기능 만들기 (#17)
  client/components/StoreDetail/AvailableServiceCard.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/pages/detail/index.tsx
  client/public/images/company1.png
  client/public/images/company2.png
  client/public/images/company3.png
  client/public/images/company4.png
  client/public/images/company5.png
  client/public/images/dogpaw.png
  client/styles/colors.ts
Labels: 🎁 기능추가, 🖍 레이아웃

#22 Feat : 상세 페이지 , 로그인 , 회원가입 백엔드 로직 추가 , 이메일 중복체크 기능 추가
  client/components/AuthButton/AuthButton.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Header/Header.tsx
  client/components/Layout/Header/Search.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/LoginForm.tsx
  client/components/SignUp/AgreeBox.tsx
  client/components/SignUp/UserForm.tsx
  client/components/StoreDetail/AvailableServiceCard.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/hooks/useDebounce.tsx
  client/hooks/useScreenX.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/auth/check.ts
  client/pages/api/auth/db.ts
  client/pages/api/auth/login.ts
  client/pages/api/auth/signup.ts
  client/pages/detail/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/signup/index.tsx
  client/public/images/company1.png
  client/public/images/company2.png
  client/public/images/company3.png
  client/public/images/company4.png
  client/public/images/company5.png
  client/public/images/dogpaw.png
  client/public/svg/Logoimg.png
  client/public/svg/MoblieLogo.png
  client/styles/colors.ts
Labels: 🎁 기능추가, 🖍 레이아웃, 🧲 API 연결

#31 Feat : 메인 홈 페이지 레이아웃 구성 , 검색 결과 페이지 레이아웃 구성
  client/components/CardImage/CardImage.tsx
  client/components/DayPickerRange/DayPickerRange.tsx
  client/components/Home/CategoryTag.tsx
  client/components/Home/PostCard.tsx
  client/components/Home/SearchBar.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/SignUp/UserForm.tsx
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/pages/search/index.tsx
  client/public/images/mainBanner.png
  client/public/images/subBanner.jpg
  client/recoil/searchValue.ts
  client/styles/colors.ts
  client/utils/dummy/dummy.ts
  client/utils/options/options.ts
  client/utils/util/index.ts
  client/utils/validate/index.ts
Labels: 🎁 기능추가, 🖍 레이아웃

#32 Feat : 상세 페이지 기능 개발 및 헤드 컴포넌트 리팩토링
  client/.env
  client/components/AuthButton/AuthButton.tsx
  client/components/Layout/Header/Header.tsx
  client/components/Layout/Header/Search.tsx
  client/components/Layout/Header/SearchBar.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/TapMenu.tsx
  client/components/StoreDetail/AvailableServiceCard.tsx
  client/components/StoreDetail/CompanyReviewCard.tsx
  client/components/StoreDetail/CompanyReviewListCard.tsx
  client/components/StoreDetail/ReviewStarGenerator.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/login/index.tsx
  client/public/images/company2.png
  client/public/images/company3.png
  client/public/images/company4.png
  client/public/images/review1.jpg
  client/public/images/review2.jpg
  client/public/images/review3.jpg
  client/public/images/review4.jpg
  client/public/images/review5.jpg
  client/public/images/review6.jpg
  client/public/svg/DesktopLogo.png
  client/public/svg/Logoimg.png
  client/public/svg/MobileLogo.png
  client/public/svg/MoblieLogo.png
  client/styles/GlobalStyle.ts
Labels: 🎁 기능추가, 🔨 리팩토링

#33 Feat : 메인 홈페이지 및 상세 페이지 레이아웃 구성 및 기능 추가
  client/.env
  client/components/AuthButton/AuthButton.tsx
  client/components/CardImage/CardImage.tsx
  client/components/DayPickerRange/DayPickerRange.tsx
  client/components/Home/CategoryTag.tsx
  client/components/Home/PostCard.tsx
  client/components/Home/SearchBar.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Header/Header.tsx
  client/components/Layout/Header/Search.tsx
  client/components/Layout/Header/SearchBar.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/TapMenu.tsx
  client/components/SignUp/UserForm.tsx
  client/components/StoreDetail/AvailableServiceCard.tsx
  client/components/StoreDetail/CompanyReviewCard.tsx
  client/components/StoreDetail/CompanyReviewListCard.tsx
  client/components/StoreDetail/ReviewStarGenerator.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/search/index.tsx
  client/public/images/company2.png
  client/public/images/company3.png
  client/public/images/company4.png
  client/public/images/mainBanner.png
  client/public/images/review1.jpg
  client/public/images/review2.jpg
  client/public/images/review3.jpg
  client/public/images/review4.jpg
  client/public/images/review5.jpg
  client/public/images/review6.jpg
  client/public/images/subBanner.jpg
  client/public/svg/DesktopLogo.png
  client/public/svg/Logoimg.png
  client/public/svg/MobileLogo.png
  client/public/svg/MoblieLogo.png
  client/recoil/searchValue.ts
  client/styles/GlobalStyle.ts
  client/styles/colors.ts
  client/utils/dummy/dummy.ts
  client/utils/options/options.ts
  client/utils/util/index.ts
  client/utils/validate/index.ts
Labels: 🎁 기능추가, 🔨 리팩토링, 🖍 레이아웃

#47 Feat : 마이페이지 레이아웃 및 컴포넌트 생성 , 회원가입 페이지 리팩토링 , 사진 추가 API 추가
  client/components/CardImage/CardImage.tsx
  client/components/CheckBox/CheckBox.tsx
  client/components/Home/SearchBar.tsx
  client/components/Input/Input.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Layout.tsx
  client/components/Mypage/AddDogModal.tsx
  client/components/Mypage/AddReviewModal.tsx
  client/components/Mypage/DogCardSwiper.tsx
  client/components/Mypage/DogProfileCard.tsx
  client/components/Mypage/LabelRadioButton.tsx
  client/components/Mypage/ReservationProcessing.tsx
  client/components/Mypage/ReservationSwiper.tsx
  client/components/Mypage/ReservedCard.tsx
  client/components/Mypage/ReservedTag.tsx
  client/components/Mypage/ReviewTable.tsx
  client/components/Mypage/UserProfileCard.tsx
  client/components/SignUp/UserForm.tsx
  client/package-lock.json
  client/package.json
  client/pages/api/file/getimg.ts
  client/pages/api/file/upload.ts
  client/pages/mypage/[userid]/index.tsx
  client/pages/signup/index.tsx
  client/tsconfig.json
  client/utils/dummy/dummy.ts
Labels: 🎁 기능추가, 🔨 리팩토링, 🖍 레이아웃, 🧲 API 연결

#48 Feat : 상세페이지, 예약주문페이지, 로그인 페이지 기능 및 스타일 추가
  client/components/AuthButton/AuthButton.tsx
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/Map/Map.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/pages/_app.tsx
  client/pages/book/index.tsx
  client/pages/login/index.tsx
Labels: 🎁 기능추가, 🔨 리팩토링, 🖍 레이아웃

#49 Feat : 마이페이지 , 디테일 페이지 레이아웃 및 기능 추가
  client/components/AuthButton/AuthButton.tsx
  client/components/CardImage/CardImage.tsx
  client/components/CheckBox/CheckBox.tsx
  client/components/Home/SearchBar.tsx
  client/components/Input/Input.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Layout.tsx
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/Map/Map.tsx
  client/components/Mypage/AddDogModal.tsx
  client/components/Mypage/AddReviewModal.tsx
  client/components/Mypage/DogCardSwiper.tsx
  client/components/Mypage/DogProfileCard.tsx
  client/components/Mypage/LabelRadioButton.tsx
  client/components/Mypage/ReservationProcessing.tsx
  client/components/Mypage/ReservationSwiper.tsx
  client/components/Mypage/ReservedCard.tsx
  client/components/Mypage/ReservedTag.tsx
  client/components/Mypage/ReviewTable.tsx
  client/components/Mypage/UserProfileCard.tsx
  client/components/SignUp/UserForm.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/file/getimg.ts
  client/pages/api/file/upload.ts
  client/pages/book/index.tsx
  client/pages/login/index.tsx
  client/pages/mypage/[userid]/index.tsx
  client/pages/signup/index.tsx
  client/tsconfig.json
  client/utils/dummy/dummy.ts
Labels: 🎁 기능추가, 🖍 레이아웃

#63 Feat : 포스트 작성 페이지 추가 및 서버 API 연결
  client/apis/AuthAPI.ts
  client/apis/AuthPostAPI.ts
  client/apis/ViewPostAPI.ts
  client/apis/getUserInfo.ts
  client/apis/index.ts
  client/apis/type/types.ts
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/components/Write/AvailableServicesAll.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/book/index.tsx
  client/pages/login/index.tsx
  client/pages/write/index.tsx
  client/styles/GlobalStyle.ts
  client/utils/options/options.ts
Labels: 🎁 기능추가, 🖍 레이아웃, 🧲 API 연결

#65 Feat : 전체 코드 리팩토링 및 API 연결
  client/apis/AuthAPI.ts
  client/apis/AuthPostAPI.ts
  client/apis/ViewPostAPI.ts
  client/apis/getUserInfo.ts
  client/apis/index.ts
  client/apis/postAPI.ts
  client/apis/type/types.ts
  client/components/BookConfirm/ConfirmCard.tsx
  client/components/BookConfirm/ConfirmCardSwiper.tsx
  client/components/CardImage/CardImage.tsx
  client/components/CeoPage/CeoProfileCard.tsx
  client/components/CeoPage/CompanyInfoCard.tsx
  client/components/CeoPage/CompanyInfoTag.tsx
  client/components/CheckBox/CheckBox.tsx
  client/components/DayPickerRange/DayPickerRange.tsx
  client/components/Home/CategoryTag.tsx
  client/components/Home/PostCard.tsx
  client/components/Home/SearchBar.tsx
  client/components/LabelInput/LabelInput.tsx
  client/components/Layout/Header/Header.tsx
  client/components/Layout/Header/SearchBar.tsx
  client/components/LoadingSpinner/LoadingSpinner.tsx
  client/components/Login/LoginForm.tsx
  client/components/Login/TapMenu.tsx
  client/components/Map/Map.tsx
  client/components/Mypage/AddDogModal.tsx
  client/components/Mypage/AddReviewModal.tsx
  client/components/Mypage/DogCardSwiper.tsx
  client/components/Mypage/DogProfileCard.tsx
  client/components/Mypage/ReservationSwiper.tsx
  client/components/Mypage/ReviewTable.tsx
  client/components/Mypage/UserProfileCard.tsx
  client/components/SignUp/CheckBoxLabel.tsx
  client/components/SignUp/Postcode.tsx
  client/components/SignUp/SignUpTab.tsx
  client/components/SignUp/UserForm.tsx
  client/components/StoreDetail/CompanyReviewListCard.tsx
  client/components/StoreDetail/SectionTitle.tsx
  client/components/StoreDetail/StoreDetail.tsx
  client/components/Write/AvailableServicesAll.tsx
  client/hooks/useIntersect.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/api/file/upload.ts
  client/pages/book/index.tsx
  client/pages/book_confirm/index.tsx
  client/pages/ceopage/[ceoid]/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/mypage/[userid]/index.tsx
  client/pages/search/index.tsx
  client/pages/write/index.tsx
  client/recoil/editOpen.ts
  client/recoil/searchValue.ts
  client/styles/GlobalStyle.ts
  client/types/post.ts
  client/utils/options/options.ts
  client/utils/validate/index.ts
Labels: 🎁 기능추가, 🔨 리팩토링, 🖍 레이아웃, 🧲 API 연결
